Repository AY2324S1-CS2103T-T11-2/tp, pull requests merged in 2023-10, with the labels that each got.

#64 Enhance the Find Interview Command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/FindInterviewCommand.java
  src/main/java/seedu/address/model/applicant/ApplicantContainsInterviewPredicate.java
  src/main/java/seedu/address/model/interview/Interview.java
  src/test/java/seedu/address/logic/commands/FindInterviewCommandTest.java
Labels: priority.Medium, type.Enhancement

#80 Add "list-i" command functionality
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/ListInterviewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListInterviewCommandTest.java
Labels: priority.High

#95 Add list interviews today method
  src/main/java/seedu/address/logic/parser/TimeParser.java
  src/test/java/seedu/address/logic/parser/TimeParserTest.java
Labels: priority.High

#98 Fix bug in DeleteInterviewCommand
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/applicant/Applicant.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Bug

#100 Fix invalid interview start and end time bug
  src/main/java/seedu/address/logic/commands/AddInterviewCommand.java
  src/main/java/seedu/address/logic/parser/AddInterviewCommandParser.java
Labels: type.Bug

#102 Bug fix for rating system
  src/main/java/seedu/address/logic/commands/RateCommand.java
  src/main/java/seedu/address/model/interview/Rating.java
Labels: type.Bug
